### PR TITLE
Compatibility for ghc 8.4.x

### PR DESCRIPTION
**Pull request by mjrussell**

### CODE REVIEW

**Comment by mjrussell** [comment]
Actually dont merge, this doesn't compile on less than < 8.2 due to `Semigroup` not being in scope

**Comment by mwotton** [comment]
looks fine, but if we want to do more of this, it might be worth maintaining a Compat.hs module that all files can pull in without CPP munging in every file?

**Comment by mjrussell** [comment]
> Compat.hs module that all files can pull in without CPP munging in every file?

Interesting..I dont have much library building experience so I've never actually done this. Agree if this keeps growing we should find a better way

**Comment by gelisam** [comment]
instead of those `#ifdef`s shenanigans, you could just add `import Data.Semigroup`, that will work with both versions of ghc.

**Pull request merged**
